### ISSUE TITLE
Auto Scroll Into view New Messages

### ISSUE THREAD

**Issue by SQL-MisterMagoo** [Blazored/Gitter#19]
When new messages arrive they should scroll into view if the view is currently at the very bottom.

**Comment by chucker** [comment]
This seems broken again (tested in Safari for macOS, Safari for iOS, Firefox). New messages arrive, but you have to manually scroll to the end.

~~It's not clear to me from the PR which code in particular is supposed to do the scrolling. Any pointers?~~ yeah, `IsScrolledToBottom` and `ScrollIntoView` is probably where I should start looking :)

**Comment by chucker** [comment]
Never mind. The scrolling works; it's the embedding `chat.js` that (at least out of the box) didn't work right for me.
