### ISSUE TITLE
Fix the CSS

### ISSUE THREAD

**Issue by SQL-MisterMagoo** [Blazored/Gitter#2]
The CSS is a mess because of stuff...

Needs sorting out so it is themeable and consistent.
Needs accessibility sorting out 
Layout needs work

**Comment by chrissainty** [comment]
I would suggest we think about swapping over to SASS to manage the styling. It will be cleaner and easier to maintain.

**Comment by SQL-MisterMagoo** [comment]
Absolutely,  fine with me

**Comment by SQL-MisterMagoo** [comment]
We should make sure there is a good layout for small screens / mobile
