### ISSUE TITLE
Small screen layout

### ISSUE THREAD

**Issue by SQL-MisterMagoo** [Blazored/Gitter#27]
I'd love to get this to the point where I can use it on my phone, but I'm not sure how we handle screen layouts with the current structure.

I'd like - but am not fixed on - a simple swipe left and right to reach different pages on mobile.

Mobile
[ Login ] <--> [ Rooms ] <--> [ Room ] <--> [ Search ]

Desktop
[ Login ] <--> [ Rooms ] [ Room ] [ Search ]

**Comment by chrissainty** [comment]
I like the idea but I’m worried about the reality of this UX. If the user
is in a load of rooms then that could lead to a lot of swiping. Also there
would be no central place to view which rooms have unread messages.

I would suggest, at least for the first instance, we go with a pop out menu
showing all rooms. We could then look at a swipe gesture as a complimentary
feature.

What do you think?

**Comment by SQL-MisterMagoo** [comment]
Yep totally get that, and totally open to suggestions.
I think you'll be best placed to guide us on this as I'm really not very good at UI/design 😁

**Comment by chrissainty** [comment]
I'll have a hack about with a few ideas, I'll cover this in #34.
