### ISSUE TITLE
Centralise the SCSS

### ISSUE THREAD

**Issue by SQL-MisterMagoo** [Blazored/Gitter#33]
In order to get the Server Side version working again, we should look to centralise the SCSS - probably into the Core project as that's where components live and the SCSS is related to them.

**Comment by SQL-MisterMagoo** [comment]
@MarkStega has expressed an interest in helping out with this.

**Comment by MarkStega** [comment]
I will definitely take this on on the morning.

**Comment by SQL-MisterMagoo** [comment]
This is now complete
