### ISSUE TITLE
Make the app responsive

### ISSUE THREAD

**Issue by chrissainty** [Blazored/Gitter#34]
When I did the initial styling is was a bit quick and dirty as I didn't want to hold up adding features for too long .

This issue covers the following outstanding items
- Make the site mobile first/just responsive at a minimum
- Introduce a good navigation experience to mobile users

**Comment by SQL-MisterMagoo** [comment]
Can you add a class/style for showing one message full screen please?

It would be great on mobile if we could either view a traditonal message list or optionally one message full page with actions to move previous/next (swipes or buttons)

**Comment by chrissainty** [comment]
Sure that should be doable... I'll have a play around.

**Comment by chrissainty** [comment]
I've raised #60 to cover the full screen/swipe functionality.
