### ISSUE TITLE
Build out DevOps pipeline

### ISSUE THREAD

**Issue by chrissainty** [Blazored/Gitter#4]
It would be good to have master being build on merges and PR requests being built before allowing merges.

Also do we want to think about deploying this somewhere?

**Comment by SQL-MisterMagoo** [comment]
Again totally agree. 
We could stick it on github pages for now

**Comment by chrissainty** [comment]
I'm going to do a little rejigging of the repo structure when I implement this, just a heads up. Shouldn't be too bad.

**Comment by SQL-MisterMagoo** [comment]
That's fine I'm very flexible about things like that
