### ISSUE TITLE
App hangs when signing in for the first time

### ISSUE THREAD

**Issue by chrissainty** [Blazored/Gitter#56]
When signing in for the first time the app requires a token. Enter the token and then click sign and remember me. App hangs sits with the loading spinner going saying attempting login...

Refresh the page and the app logs straight in without issue.

I've not tested this on server-side only client-side.

**Comment by SQL-MisterMagoo** [comment]
I've got a fix for that...

**Comment by chrissainty** [comment]
Thought you might 😄
